unit BlueBamboo.Consts;

interface

const
  BLUEBAMBOO_BLUETOOTH_UUID = '{00001101-0000-1000-8000-00805F9B34FB}';
  BLUEBAMBOO_CARRIAGE_RETURN: TArray<byte> = [$0D];
  BLUEBAMBOO_FEED_LINE: TArray<byte> = [$0A];
  BLUEBAMBOO_FEED_PAPER: TArray<byte> = [$1B, $4A];
  BLUEBAMBOO_FEED_N_LINES: TArray<byte> = [$1B, $64];
  BLUEBAMBOO_BAR_CODE: TArray<byte> = [$1D, $6B];
  BLUEBAMBOO_PDF417_BAR_CODE_3: TArray<byte> = [$1D, $6B, $10];
  BLUEBAMBOO_PDF417_BAR_CODE_7: TArray<byte> = [$1D, $6B, $11];
  BLUEBAMBOO_DEFAULT_LINE_SPACE: TArray<byte> = [$1B, $32];
  BLUEBAMBOO_SET_LINE_SPACE: TArray<byte> = [$1B, $33];
  BLUEBAMBOO_SELECT_ACP_OR_UTF8_CODING: TArray<byte> = [$1B, $4B];
  BLUEBAMBOO_SELECT_AN_INTERNATIONAL_CHARACTER_SET: TArray<byte> = [$1B, $52];
  BLUEBAMBOO_SELECT_PRINT_MODE: TArray<byte> = [$1B, $21];
  BLUEBAMBOO_TURN_UNDERLINE_MODE: TArray<byte> = [$1B, $2D];
  BLUEBAMBOO_SELECT_CHARACTER_SIZE: TArray<byte> = [$1D, $21];
  BLUEBAMBOO_TURN_REVERSE_PRINTING_MODE: TArray<byte> = [$1D, $42];
  BLUEBAMBOO_TURN_KEYPAD_MODE: TArray<byte> = [$1B, $63, $35];
  BLUEBAMBOO_SET_ABSOLUTE_PRINT_POSITION: TArray<byte> = [$1B, $24];
  BLUEBAMBOO_SELECT_JUSTIFICATION_MODE: TArray<byte> = [$1B, $61];
  BLUEBAMBOO_HORIZONTAL_TAB: TArray<byte> = [$09];
  BLUEBAMBOO_SET_HORIZONTAL_TAB_POSITIONS: TArray<byte> = [$1B, $44];
  BLUEBAMBOO_SET_LEFT_MARGIN: TArray<byte> = [$1D, $4C];
  BLUEBAMBOO_PRINT_BIT_IMAGE: TArray<byte> = [$1D, $76, $30];


implementation

end.
